name: release

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    if: github.actor == 'matteo-chesi'
    strategy:
      matrix:
        include:
          - arch: x86_64
            build_os: opensuse-15.5
          - arch: x86_64
            build_os: opensuse-15.6
    env:
      os: opensuse
      os_version: 15.5
    runs-on: chesim-zinal-login
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          ./clean.sh --build && \
          ./build.sh --build-os ${{ matrix.build_os }}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: "tmp/artifacts/*"
          allowUpdates: true
          replacesArtifacts: false
          draft: false
          prerelease: false
